### ISSUE TITLE
Add tags to records

### ISSUE THREAD

**Issue by glensc** [cloudposse/terraform-cloudflare-zone#46]
### Describe the Feature

There's no "tags" in record:
- https://github.com/cloudposse/terraform-cloudflare-zone/blob/3073cc39498d44ec44f023ffe1ec8d03d664ebf7/main.tf#L34-L44

### Expected Behavior

Also, i tried to pass context.tags via atmos config, and then it totally blew up

```yml
components:
  terraform:
    cloudflare-zone:
      vars:
        context:
          tags:
            - "cloudflare-terraform"
```

### Use Case

.

### Describe Ideal Solution

.
